fix: AttributeError: type object 'Sound' has no attribute 'get_num_channels'
StreamingSound.streamIsPlaying() is currently implemented by returning Sound.get_num_channels().
This will result in an error since the Sound class has no method get_num_channels(). It does have a method isPlaying() which calls get_num_channels() on its self.sound object. Use this method instead.